export const EMPLOYMENT_TYPES = [
    "Full-Time",
    "Part-Time",
    "Permanent",
    "Temporary",
    "Fixed-Term Contract",
    "Contract",
    "Bank",
    "Agency",
    "Locum",
    "Casual",
    "Zero-Hours Contract",
    "Self-Employed",
    "On-Site",
    "Hybrid",
    "Remote",
    "Flexible Working",
    "Apprenticeship",
    "Internship",
    "Graduate Programme",
    "Student Placement",
    "Trainee Position",
    "Newly Qualified",
    "Visa Sponsorship Available",
    "International Recruitment",
    "Overseas Applicants Welcome",
    "Relocation Support Available",
] as const

export type EmploymentType = (typeof EMPLOYMENT_TYPES)[number]
